# Generated by Django 5.1.2 on 2025-01-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('LeetCode', 'LeetCode'), ('CodeChef', 'CodeChef'), ('Codeforces', 'Codeforces')], max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('last_rating', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles', to='subscriptions.subscriber')),
            ],
            options={
                'unique_together': {('subscriber', 'platform_name')},
            },
        ),
    ]
