# Generated by Django 5.1.2 on 2025-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='contests_attended',
            field=models.IntegerField(default=0),
        ),
    ]
