# Generated by Django 5.1.2 on 2025-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_platformprofile_contests_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='contests_attended',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='last_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='platform_name',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('CodeChef', 'CodeChef'), ('Codeforces', 'Codeforces')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='problems_solved',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
