# Generated by Django 5.1.5 on 2025-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_platformprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
