# Generated by Django on 2026-02-18  

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriber_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_rating', models.IntegerField(blank=True, default=None, null=True)),
                ('problems_solved', models.IntegerField(blank=True, default=None, null=True)),
                ('contests_attended', models.IntegerField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=models.CASCADE, related_name='snapshots', to='subscriptions.platformprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
