name: Trigger Leaderboard API

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  call_api:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your repository

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run trigger_leaderboard.py
      run: |
        python trigger_leaderboard.py
